# Generated by Django 4.1.3 on 2022-11-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='practice_counts_for_time',
            field=models.BooleanField(default=True, help_text='Time spent on practice tests counts towards the minimum time'),
        ),
        migrations.AddField(
            model_name='coursepageviewinstance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_page_view_instances', to='core.student'),
        ),
    ]
