# Generated by Django 4.1.3 on 2022-11-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Home page description of the course'),
        ),
    ]
