# Generated by Django 4.1.3 on 2022-11-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_practice_counts_for_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepageviewinstance',
            name='course_test_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_page_view_instances', to='core.coursetestinstance'),
        ),
    ]
