# Generated by Django 4.1.3 on 2022-11-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coursepageviewinstance_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetest',
            name='only_practice_test',
            field=models.BooleanField(default=False, help_text='When turned on only test only counts for practice'),
        ),
    ]
