# Generated by Django 4.1.3 on 2022-11-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_multiplechoicetestquestion_question_post_answer_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseviewinstance',
            name='first_page_view',
        ),
        migrations.RemoveField(
            model_name='courseviewinstance',
            name='last_page_view',
        ),
    ]
