# Generated by Django 4.1.3 on 2022-11-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coursepageviewinstance_course_test_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetest',
            old_name='max_number_of_question',
            new_name='max_number_of_questions',
        ),
    ]
