# Generated by Django 4.1.3 on 2022-11-14 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_max_number_of_question_coursetest_max_number_of_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetest',
            name='maximum_practice_tests',
        ),
        migrations.AddField(
            model_name='coursetest',
            name='passing_percentage',
            field=models.IntegerField(default=60, help_text='The minimum percentage needed to pass'),
        ),
        migrations.AddField(
            model_name='coursetestinstance',
            name='retake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coursetestinstance'),
        ),
        migrations.AlterField(
            model_name='coursetest',
            name='course_fixed_answer_length',
            field=models.IntegerField(default=4, help_text='\n        The fixed length of the answers if "Is course fixed answer length" is checked.\n        0 generates all questions\n        '),
        ),
        migrations.AlterField(
            model_name='multiplechoicetestquestion',
            name='multiple_choice_answer_length',
            field=models.IntegerField(default=4, help_text='Total number of answers that will appear in the questions generated. 0 generates all'),
        ),
    ]
