# Generated by Django 4.1.3 on 2022-11-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_coursetest_maximum_practice_tests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='is_live_only',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='is_practice_only',
        ),
    ]
